# Generated by Django 4.1.7 on 2023-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_bibleverse_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('html', models.TextField()),
                ('hebrew', models.TextField()),
            ],
            options={
                'db_table': 'genesis',
            },
        ),
        migrations.DeleteModel(
            name='BibleVerse',
        ),
    ]
